spring:
  datasource:
    url: URL
    username: USERNAME
    password: PASSWORD
    driver-class-name: DRIVER
  jpa:
    hibernate:
      #            ddl-auto: create-drop
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: DATABASE
    database-platform: PLATFORM
  ai:
    openai:
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: AI_MODEL
      api-key: API_KEY